# Generated by Django 4.2 on 2026-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plan_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Awaiting Approval'), ('approved', 'Approved - Ready to Build'), ('building', 'Building'), ('success', 'Success'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProjectMessage',
        ),
    ]
