# Generated by Django 4.2 on 2026-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_plan_summary_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frontend',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
    ]
