# apps/projects/generator.py
import json
import re
import logging
from apps.chat.llm_wrapper import LLMWrapper
from apps.knowledge.query import query_knowledge

logger = logging.getLogger(__name__)
llm = LLMWrapper()

SYSTEM_PROMPT = """
You are CodeForge, a senior software architect. Your task is to generate a complete, working project based on the user's request.

You must output a **valid JSON** object with the following structure:
{
  "project_name": "string",
  "framework": "string (django, laravel, springboot, flask, react, pygame, python)",
  "summary": "A brief human‑readable summary of what this project does.",
  "files": [
    {"path": "relative/path/to/file", "content": "full file content"},
    ...
  ],
  "commands": ["shell command 1", "shell command 2", ...]
}

**CRITICAL RULES:**
- The "files" array must contain ALL files needed for the project to run.
- Include a README.md with setup instructions.
- Include a requirements.txt, package.json, composer.json, or pom.xml as appropriate.
- The content must be the full, correct source code – not placeholders.
- The "commands" should include installation, migration, and run commands.
- The "summary" should be a clear, concise description of the project.

Return ONLY the JSON, no extra text.
"""

# ============================================================
# FALLBACK TEMPLATES – using __PROJECT_NAME__ placeholder
# ============================================================

FALLBACK_TEMPLATES = {
    "django": {
        "project_name": "django_project",
        "framework": "django",
        "summary": "A Django web application with a simple blog or default structure.",
        "files": [
            {"path": "__PROJECT_NAME__/__init__.py", "content": ""},
            {"path": "__PROJECT_NAME__/settings.py", "content": "import os\nfrom pathlib import Path\n\nBASE_DIR = Path(__file__).resolve().parent.parent\nSECRET_KEY = 'django-insecure-fallback-key'\nDEBUG = True\nALLOWED_HOSTS = []\n\nINSTALLED_APPS = [\n    'django.contrib.admin',\n    'django.contrib.auth',\n    'django.contrib.contenttypes',\n    'django.contrib.sessions',\n    'django.contrib.messages',\n    'django.contrib.staticfiles',\n]\n\nMIDDLEWARE = [\n    'django.middleware.security.SecurityMiddleware',\n    'django.contrib.sessions.middleware.SessionMiddleware',\n    'django.middleware.common.CommonMiddleware',\n    'django.middleware.csrf.CsrfViewMiddleware',\n    'django.contrib.auth.middleware.AuthenticationMiddleware',\n    'django.contrib.messages.middleware.MessageMiddleware',\n    'django.middleware.clickjacking.XFrameOptionsMiddleware',\n]\n\nROOT_URLCONF = '__PROJECT_NAME__.urls'\n\nTEMPLATES = [\n    {\n        'BACKEND': 'django.template.backends.django.DjangoTemplates',\n        'DIRS': [],\n        'APP_DIRS': True,\n        'OPTIONS': {\n            'context_processors': [\n                'django.template.context_processors.debug',\n                'django.template.context_processors.request',\n                'django.contrib.auth.context_processors.auth',\n                'django.contrib.messages.context_processors.messages',\n            ],\n        },\n    },\n]\n\nWSGI_APPLICATION = '__PROJECT_NAME__.wsgi.application'\n\nDATABASES = {\n    'default': {\n        'ENGINE': 'django.db.backends.sqlite3',\n        'NAME': BASE_DIR / 'db.sqlite3',\n    }\n}\n\nLANGUAGE_CODE = 'en-us'\nTIME_ZONE = 'UTC'\nUSE_I18N = True\nUSE_TZ = True\n\nSTATIC_URL = 'static/'\nDEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'\n"},
            {"path": "__PROJECT_NAME__/urls.py", "content": "from django.contrib import admin\nfrom django.urls import path\n\nurlpatterns = [\n    path('admin/', admin.site.urls),\n]\n"},
            {"path": "__PROJECT_NAME__/wsgi.py", "content": "import os\nfrom django.core.wsgi import get_wsgi_application\n\nos.environ.setdefault('DJANGO_SETTINGS_MODULE', '__PROJECT_NAME__.settings')\napplication = get_wsgi_application()\n"},
            {"path": "manage.py", "content": "#!/usr/bin/env python\nimport os\nimport sys\n\ndef main():\n    os.environ.setdefault('DJANGO_SETTINGS_MODULE', '__PROJECT_NAME__.settings')\n    try:\n        from django.core.management import execute_from_command_line\n    except ImportError as exc:\n        raise ImportError(\"Couldn't import Django\") from exc\n    execute_from_command_line(sys.argv)\n\nif __name__ == '__main__':\n    main()\n"},
            {"path": "requirements.txt", "content": "Django>=4.2"},
            {"path": "README.md", "content": "# __PROJECT_NAME__\n\nA Django project generated by CodeForge.\n\n## Setup\n\n1. Install dependencies:\n   ```\n   pip install -r requirements.txt\n   ```\n2. Run migrations:\n   ```\n   python manage.py migrate\n   ```\n3. Run the server:\n   ```\n   python manage.py runserver\n   ```\n"}
        ],
        "commands": ["pip install -r requirements.txt", "python manage.py migrate", "python manage.py runserver"]
    },

    # ... (all other framework templates remain the same as before – I'll include them in the final code block)
}

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def sanitize_project_name(name):
    """Convert a string to a valid Python identifier."""
    # Remove invalid characters
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    # Remove leading underscores or digits
    name = re.sub(r'^[^a-zA-Z]+', '', name)
    # If empty, use default
    if not name or name == 'config':
        return 'django_project'
    return name

def apply_template_replacements(template, project_name):
    """Replace __PROJECT_NAME__ in all file paths and contents."""
    for file_spec in template["files"]:
        # Replace in path
        file_spec["path"] = file_spec["path"].replace("__PROJECT_NAME__", project_name)
        # Replace in content
        file_spec["content"] = file_spec["content"].replace("__PROJECT_NAME__", project_name)
    # Also update the project_name field itself
    template["project_name"] = project_name
    return template

def generate_plan(user_prompt, context_chunks=None):
    prompt_lower = user_prompt.lower()
    detected_framework = None

    if "django" in prompt_lower:
        detected_framework = "django"
    elif "laravel" in prompt_lower:
        detected_framework = "laravel"
    elif "spring" in prompt_lower or "springboot" in prompt_lower:
        detected_framework = "springboot"
    elif "flask" in prompt_lower:
        detected_framework = "flask"
    elif "react" in prompt_lower:
        detected_framework = "react"
    elif "pygame" in prompt_lower or "game" in prompt_lower:
        detected_framework = "pygame"
    else:
        detected_framework = "python"

    if detected_framework in FALLBACK_TEMPLATES:
        template = FALLBACK_TEMPLATES[detected_framework].copy()

        # Generate a clean project name from the user prompt
        words = user_prompt.split()[:4]
        raw_name = "_".join([w.lower() for w in words if w.isalnum()])
        project_name = sanitize_project_name(raw_name)

        # Apply replacements
        apply_template_replacements(template, project_name)

        logger.info(f"Generated plan for project: {project_name} (framework: {detected_framework})")
        return template

    # Fallback to LLM (if needed)
    try:
        prompt = f"User request: {user_prompt}\n"
        if context_chunks:
            prompt += "\nRelevant context:\n" + "\n\n".join(context_chunks)
        prompt += "\n\nGenerate a complete project plan as JSON."

        full_response = ""
        for chunk in llm.generate_stream(prompt, system_override=SYSTEM_PROMPT):
            full_response += chunk

        cleaned = re.sub(r'```json\s*', '', full_response)
        cleaned = re.sub(r'```\s*', '', cleaned)
        start = cleaned.find('{')
        end = cleaned.rfind('}') + 1
        if start != -1 and end > start:
            json_str = cleaned[start:end]
            plan = json.loads(json_str)
            if 'files' in plan and 'commands' in plan and len(plan.get('files', [])) >= 3:
                # Sanitize and replace project name if present
                if 'project_name' in plan:
                    plan['project_name'] = sanitize_project_name(plan['project_name'])
                return plan
    except Exception as e:
        logger.error(f"LLM plan generation failed: {e}")

    # Ultimate fallback – use python template
    python_template = FALLBACK_TEMPLATES.get("python", {}).copy()
    if python_template:
        project_name = sanitize_project_name("python_script")
        apply_template_replacements(python_template, project_name)
        return python_template
    else:
        # Hardcoded fallback
        return {
            "project_name": "project",
            "framework": "python",
            "summary": "A simple Python project.",
            "files": [{"path": "main.py", "content": "print('Hello World')"}],
            "commands": ["python main.py"]
        }

# ============================================================
# SCRIPT GENERATION (single‑file snippets)
# ============================================================

SCRIPT_SYSTEM_PROMPT = """
You are CodeForge, a senior software engineer. The user wants a simple script or code snippet.
Provide only the code, without any extra text or explanation.
If the user asks for a specific language, use that language. Otherwise, use Python.
Keep the code clean and functional.
"""

def generate_script(user_prompt, context_chunks=None):
    """Generate a single-file script using the LLM."""
    prompt = f"Write code for: {user_prompt}"
    if context_chunks:
        prompt += "\n\nRelevant context:\n" + "\n\n".join(context_chunks)
    response = ""
    for chunk in llm.generate_stream(prompt, system_override=SCRIPT_SYSTEM_PROMPT):
        response += chunk
    import re
    match = re.search(r'```(\w+)?\n(.*?)```', response, re.DOTALL)
    if match:
        return match.group(2).strip()
    return response.strip()